format = """
[](#E6C384)\
$os\
$username\
[](bg:#9ecd6f fg:#E6C384)\
$directory\
[](fg:#9ecd6f bg:#4e8ca2)\
$git_branch\
$git_status\
[](fg:#4e8ca2 bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#282727)\
$status\
[ ](fg:#282727)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#E6C384 fg:#000000 bold"
style_root = "bg:#E6C384 fg:#000000 bold"
format = '[$user ]($style)'
disabled = false

[status]
style = 'bg:#282727 fg:#FF5D62 bold'
format = '[ $symbol$status $signal_name ]($style)'
map_symbol = false
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#E6C384"
disabled = true # Disabled by default

[directory]
style = "bg:#9ecd6f fg:#000000 bold"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 0

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#4e8ca2 bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4e8ca2 bold"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
