
[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[general]
live_config_reload = true
import = ["/home/sumer/.config/alacritty/alacritty_theme.toml"]

[terminal]

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
builtin_box_drawing = true
size = 9.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/bash"

[window]
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
