require("user.options")
require("user.keymaps")
require("user.plugins-config")
require("user.colorschemes")
require("user.cmp")
require("user.lsp")
require("user.icons")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comments")
require("user.git-signs")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.harpoon")
--[[ require("user.treesitter-rainbow-delimiters") ]]
